[supervisord]
nodaemon=true

[program:selenium]
command=/opt/bin/entry_point.sh
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:selgrid]
command=gunicorn -b 0.0.0.0:8080 app:app
directory=/opt/selgrid
autostart=true
autorestart=true
priority=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PYTHONUNBUFFERED="1",SELENIUM_REMOTE_URL="http://127.0.0.1:4444/wd/hub"
